### PR TITLE
ccmp, locl, mark, mkmk, and gdef features

### LINKED ISSUE #217: Implement IJacute and ijacute for Dutch language
Relevant:

https://typedrawers.com/discussion/1294/how-do-you-implement-ijacute-and-ijacute

### LINKED ISSUE #367: Add /ringbelow, add anchors to base glyphs & accents. Then, add `mark` feature. (Request: IAST and ISO 15919 Glyphs)
Many of the glyphs used in [IAST (International Alphabet of Sanskrit Transliteration)](https://en.wikipedia.org/wiki/International_Alphabet_of_Sanskrit_Transliteration) and [ISO 15919 (Transliteration of Devanagari and related Indic scripts into Latin characters)](https://en.wikipedia.org/wiki/ISO_15919) are already covered under Latin Extended blocks. Some of them are not.

I am particularly interested in these glyphs:

- Ṝ = U+1E5C LATIN CAPITAL LETTER R WITH DOT BELOW AND MACRON
- ṝ = U+1E5D LATIN SMALL LETTER R WITH DOT BELOW AND MACRON
- Ḹ = U+1E38 LATIN CAPITAL LETTER L WITH DOT BELOW AND MACRON
- ḹ = U+1E39 LATIN SMALL LETTER L WITH DOT BELOW AND MACRON
- ̥ = U+0325 COMBINING RING BELOW (Used in R̥ r̥ L̥ l̥ R̥̅ r̥̅ L̥̅ l̥̅, which are ISO 15919 characters for vocalic Rs and Ls)
- Ṁ = U+1E40 LATIN CAPITAL LETTER M WITH DOT ABOVE
- ṁ = U+1E41 LATIN SMALL LETTER M WITH DOT ABOVE

### LINKED ISSUE #368: Add glyph /Jacute, OR find how to combine `.case` accents with uppercase base glyphs.
**Problem description**

The J with a combining acute looks wrong, probably because other caps get an `acutecomb.case` in precomposed glyphs, while the J gets a normal combining acute (drawn specifically for the lowercase) .

image

**Expected behavior**

If an uppercase glyph is likely to have an acute or other accent, it either needs a way to get the correct `case` accents, or it needs to be precomposed.

### LINKED ISSUE #440: Mark feature in Static fonts isn't able to be built as variable font
**Problem description**
The feature code for the `mark`, `mkmk`, `gdef` feature for the static fonts causes fontmake to not be able to build the variable font. Error is `VarLibMergeError: ((2, [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]), 'int', '.LookupCount', 'Feature', '.Feature', 'FeatureRecord', '[0]', 'list', '.FeatureRecord', 'FeatureList', '.FeatureList', 'GPOS', '.table', 'table_G_P_O_S_')`.

Currently, the `mark`, `mkmk`, and `gdef` features are being built by fontmake for the var font.

**Expected behavior**
The same OT code can work for both fonts.

**To Reproduce**

To `build_variable.py` add:

`from fontParts.fontshell import RFont as Font` to the head of the file

Change line 7 to `from utils import getFiles, make_mark_mkmk_gdef_feature`

and then add these lines after line 21 (the end of the `buildFeatures` function)
```
    for ufo in ufos:
        font = Font(ufo)
        mark_mkmk_gdef = make_mark_mkmk_gdef_feature(font)
        font.features.text += mark_mkmk_gdef
        font.save(font.path)
    print("🏗  Added mark, mkmk, and GDEF to features")
```

Then run the variable fonts build.

**Environment (please complete the following information):**
Standard build environment.

**Additional context**
To pick this apart, the UFOs that are used for the variable fonts should be built with the static OT code (see above to reproduce). Those UFOs should be built with fontmake as TTFs, and then the GPOS tables compared to see where the difference is, along with an examination of the OT code for what might be triggering the issue. So far the OT code seems as though it should be making the same number of lookups in all fonts, but more investigation is needed.

### PR DESCRIPTION
**Pull request by benkiel**
`ccmp` and `locl` feature for all fonts. 

Builds a `mark`, `mkmk`, and `gdef` feature for static fonts (currently those features are built by `fontmake` for the variable font (see #440). This _may_ mean that marks behave differently between the static and variable font.

Some code fixups and style fixups also happened in this branch. Beta fonts for testing in `/fonts`

This closes #217, closes #367, closes #368, and closes #440.

### CODE REVIEW

**Comment by arrowtype** [comment]
Thank you, Ben! This is an awesome upgrade.

In my initial testing, I’ve verified a few things are working better than before:
- Combining accents are working mostly very well!
- I’m especially excited that the `.case` versions of combining accents are being attached to uppercase glyphs, while normal accents are attaching to lowercase glyphs.
- Localization features like a Dutch `ij` seem to be working well.
- Mark-to-mark attachment seems to be working well, e.g. `n` + `macroncomb` + `caroncomb` stacks.

Things I’ve noticed that (I think) I can easily fix on my own, after merging:
- The `R̊` isn’t yet working, but I think this is a simple fix of add a `_top` anchor to the `rincomb` and `ringcomb.case` in the sources. 
- The `K̇` is a bit off in the slanted styles, but this is definitely just a simple fix of moving anchors in the slanted sources.

## One open question

In the static fonts, combining accents don’t yet seem to be working for feature-activated glyphs such as `a.italic`. (These are working well in the variable font.) For example, `ǎ n̄` are failing in Sans & Mono statics, while `r̊` is failing in Mono statics. This is the case whether these are set up via `rvrn` or applied via features like `ss01`. I am pretty sure I’ll merge this and make a new release, because the variable font seems to be working perfectly, and the statics are like 80% better. Also, this might be an upstream issue with the ufo2ft feature generator. But, if we were to fix the statics, would you be willing to speculate how we might do this?

## Screenshot of testing

I tested this with FontGoggles.

The top five rows are statics of Version 1.075 (from this PR), the sixth row is the variable 1.075 (also from this PR), and the bottom two are version 1.074 (current/previous).

image

**Comment by arrowtype** [comment]
## Additional follow-up question

There are still a few gaps before this can fully close #440. Characters with one mark attached, like `R̥ r̥`, are working, but characters with two attached marks, like `Ḹ ḹ` are not – even if those combining marks are attaching as expected, individually, (like `L̄ Ḷ`).

image

**Comment by arrowtype** [comment]
Ultimately, I think we should merge this. I think it nails issues #217, #368, and #440, but doesn’t yet close #367.

It would be great to chat (either here or elsewhere) about what it might take to completely close #367.

I’ll merge this and close those issues later today, unless @benkiel prefers something else.

**Comment by benkiel** [comment]
> but characters with two attached marks, like Ḹ ḹ are not – even if those combining marks are attaching as expected, individually

I wonder if this is because those glyphs are getting transformed to their `Ldotbelow` forms, which don't have anchors...

**Comment by benkiel** [comment]
> The R̊ isn’t yet working, but I think this is a simple fix of add a _top anchor to the rincomb and ringcomb.case in the sources.

`ringcomb.case` is missing the `_top` anchor, it is there in the `ringcomb`, fyi. That's why it works in lc but not UC

**Comment by arrowtype** [comment]
Thanks for specifying the exact cause of the R-ring issue! I’ve added the the `_top` anchor to `ringcomb.case` in the main branch.

Because this PR only has improvements and no regressions that I know of, I’ll merge it, and close the issues it closes, and we can separate plan out how to close any remaining issues.

Thanks for all the really good work here!

**Comment by arrowtype** [comment]
- [ ] To fix the `Ṝ ṝ Ḹ ḹ` issue, I will add top anchors to R dot below etc 
  - [ ] When I do, I’ll add the R dot below and L dot below to the `base_uc` class in  `src/features/features/ccmp.fea`
  - [ ] We will also need to update `mastering/utils.py`

**Pull request merged**
