### PR TITLE
Clarify licensing and disclaimers

### PR DESCRIPTION
**Pull request by chrissimpkins**
This PR modifies the README file with an explicit description of the license and replaces the Disclaimer block with text that points to your OFL 1.1 license.  

The license specified disclaimers are likely to be what you want to point out to users rather than drafting your own legalese.  This should cover the disclaimers that you need to provide.  

> THE FONT SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO ANY WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT
OF COPYRIGHT, PATENT, TRADEMARK, OR OTHER RIGHT. IN NO EVENT SHALL THE
COPYRIGHT HOLDER BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
INCLUDING ANY GENERAL, SPECIAL, INDIRECT, INCIDENTAL, OR CONSEQUENTIAL
DAMAGES, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
FROM, OUT OF THE USE OR INABILITY TO USE THE FONT SOFTWARE OR FROM
OTHER DEALINGS IN THE FONT SOFTWARE.

The README documentation that currently states:

> "Feel free to use/remix these scripts in other projects."

is not entirely consistent with the SIL OFL 1.1.  This is a copyleft license and derivatives from  sources here (whether modified or used as is) must be distributed under SIL OFL 1.1 (my emphasis below):

> "Font Software" refers to the set of files released by the Copyright
Holder(s) under this license and clearly marked as such. This may
include **source files, build scripts and documentation**.

> 5) The Font Software, modified or unmodified, in part or in whole,
**must be distributed entirely under this license, and must not be
distributed under any other license**. The requirement for fonts to
remain under this license does not apply to any document created
using the Font Software.

### CODE REVIEW

**Comment by arrowtype** [comment]
Hey Chris, thanks for the helpful clarification!

**Comment by davelab6** [comment]
> Like any Python scripts, read through them and be generally familiar with what they do before running them. Also, use Git and/or backups when you are using scripts to design. 

This was a nice note, maybe good to retain

**Comment by chrissimpkins** [comment]
@davelab6 For derivative build scripts, does an entire project need to be licensed under SIL OFL or is it acceptable to dual license with the derived build source files only under OFL?  Type design source and documentation in other projects based on a project's build files can be non-OFL or no?  I don't understand this part of the license and where the 'derivative' line is drawn.

**Comment by arrowtype** [comment]
I was curious about dual-licensing, as well. Based on a quick chat with Dave, I _think_ that other projects can use/modify and bundle scripts, so long as those specific scripts retain the OFL license – but that license doesn't need to be applied to the overall project. However, to avoid ambiguity by having an OFL license in a sub-directory, other authors may wish to keep OFL scripts separate from their main project repos.

In the future, I may split out the scripts into Apace 2.0 repos, to help remove this ambiguity, while keeping the font licensed under the OFL.

I've made a new PR to try to clarify this, and include a helpful explanation for others in the readme. Maybe we could discuss further in there? :) https://github.com/arrowtype/recursive/pull/293

**Pull request merged**
