### PR TITLE
Mastering scripts

### PR DESCRIPTION
**Pull request by benkiel**
Build script for mastering. See readme for the description of their use. This also includes a fixup to the ssXX feature.

### CODE REVIEW

**Comment by arrowtype** [comment]
This is looking really excellent. I'm really lucky to have your help on this, @benkiel!

After installing updated dependencies, I'm having a hiccup in trying to run your font prep script, however. 

```
▶ python build.py --files --version 1.031          
🚚 Building files for mastering

🚚 Generating sources
🏗  Copying files
🏗  Opening sources
🏗  Checking family name
🏗  Removing non-exporting glyphs
🏗  Clearing guides
🏗  Removing glyphs that aren't in every font
🏗  Removing non-compatible glyphs
🏗  Making kerning compatible
🏗  Sorting glyph order to be common
🏗  Setting production names
🏗  Setting version
🏗  Closing and saving sources
🏗  Checking full design space
Traceback (most recent call last):
  File "build.py", line 55, in <module>
    files = buildFiles(version=version)
  File "/Users/stephennixon/type-repos/recursive/mastering/build_files.py", line 95, in buildFiles
    makeSources(ds, paths["src"], version)
  File "/Users/stephennixon/type-repos/recursive/mastering/build_files.py", line 72, in makeSources
    prep(os.path.join(src, ds), version)
  File "/Users/stephennixon/type-repos/recursive/mastering/prep_fonts.py", line 488, in prep
    dsc.checkEverything()
  File "/Users/stephennixon/type-repos/recursive/venv/lib/python3.7/site-packages/designspaceProblems/__init__.py", line 137, in checkEverything
    self.checkDesignSpaceGeometry()
  File "/Users/stephennixon/type-repos/recursive/venv/lib/python3.7/site-packages/designspaceProblems/__init__.py", line 244, in checkDesignSpaceGeometry
    self.mapper = AxisMapper(self.ds.axes)
  File "/Users/stephennixon/type-repos/recursive/venv/lib/python3.7/site-packages/ufoProcessor/varModels.py", line 20, in __init__
    self._makeWarpFromList(a.name, mapData)
  File "/Users/stephennixon/type-repos/recursive/venv/lib/python3.7/site-packages/ufoProcessor/varModels.py", line 38, in _makeWarpFromList
    self.models[axisName] = VariationModel(mapLocations, axisOrder=['w'])
  File "/Users/stephennixon/type-repos/recursive/venv/lib/python3.7/site-packages/fontTools/varLib/models.py", line 195, in __init__
    raise ValueError("locations must be unique")
ValueError: locations must be unique
```

I haven't changed the designspace at all ... Is there anything you suggest I try to get past this error?

**Comment by benkiel** [comment]
@arrowtype correct, that's why the requirements file makes `ufoProcessor` be `1.8` or higher, it forces `afdko` to not install version `1.0.6` of `ufoProcessor`. The Adobe team is doing this currently because something in `ufoProcessor 1.8` was breaking some of the the `afdko` tests (https://github.com/adobe-type-tools/afdko/issues/408#issuecomment-555245593). You need version `1.8` to do the rule mapping, etc.

**Comment by arrowtype** [comment]
Thanks for the info about ufoProcessor!

I've been able to build all statics & variable fonts, and things are looking great so far. The `checkOutlines` result has flagged some useful issues, and I am hopefully that some or most can be solved in the sources, or via a helper script if not (e.g. for overlapping contours).

One question before I merge: it seems like "RIBBI" style linking is working well on windows, but not yet on Mac (as tested in VS Code and Sketch). Did you happen to have the chance to test that specific question? Might I be missing some step (e.g. calling the incorrect font name in my VS Code settings)?

**Comment by arrowtype** [comment]
Here's an open issue for the last question: https://github.com/arrowtype/recursive/issues/153

Another question: it seems that code ligatures are not currently working in the static builds (though they do seem to be working in the variable builds): https://github.com/arrowtype/recursive/issues/287

And finally, I think we will need to add a suffix into static font names to ensure that they are unambiguously different than the variable font name (which should be the base font).

This is described in detail at https://github.com/arrowtype/recursive/issues/288.

Would it be possible for you to look into these issues, Ben? If not, I could probably look into the name suffixes and code ligatures, but I would really appreciate your help in getting RIBBI style-linking working well.

**Comment by benkiel** [comment]
@arrowtype With a new suffix for the statics, it may fix what you see in VS Code and Sketch, as that may be due to having the variable and static fonts installed, will look into.

**Pull request merged**
