### PR TITLE
vietnamese diacritics into Sans

### PR DESCRIPTION
**Pull request by LisaHuang2017**
From issue #87

### CODE REVIEW

**Comment by LisaHuang2017** [comment]
Added corrections on /equal_greater.code ligature in Mono from issue #176

**Comment by arrowtype** [comment]
Before
image

After
image


This is a helpful update, but I'd still like to have the arrowheads be a bit steeper and pointier in this.

**Comment by LisaHuang2017** [comment]
Okay, will do. I thought you said that for B weights they only needed to be lighter :)

**Comment by arrowtype** [comment]
> I thought you said that for B weights they only needed to be lighter

Sorry, I may have not written very clearly. It felt like the Casual B had the right shaping, but the others weren't quite steep enough. But, I think things are probably pretty good, and I might circle back and fiddle with this one a bit more. Thanks for working on it!

**Pull request merged**
