### PR TITLE
Fix Ldot compatibility

### PR DESCRIPTION
**Pull request by LisaHuang2017**
Issue #216 fixed!

### CODE REVIEW

**Comment by LisaHuang2017** [comment]
WIP for issue #208

**Comment by LisaHuang2017** [comment]
fixed issue #155

**Comment by LisaHuang2017** [comment]
Checked issue #209 but most of them appeared all good... another way might be needed to find out the reason why they are not compatible yet.

**Comment by LisaHuang2017** [comment]
Worked on issue #210

**Comment by arrowtype** [comment]
Great work here, Lisa! Thank you!

**Pull request merged**
