### PR TITLE
Re-work mastering to account for name changes in the liga feature

### LINKED ISSUE #320: Some standard ligatures not available in Static Italic fonts, as desired (fi, fl, ffi, ffl)
**Problem description**

These are availabe in the variable font, but not yet in the static italics.

**Expected behavior**
fi, fl, ffi, ffl should automatically be ligatures in the Italic static fonts. They are not.

**To Reproduce**

**Environment (please complete the following information):**
- OS: macOS 10.15.3
- Fonts: [v1.042](https://github.com/arrowtype/recursive/tree/7ff677f7b54f0a188e08abc18b5b2ece27556000/fonts/Recursive-Beta_1.042)

**Additional context**

Will document more as I dig into this.

### PR DESCRIPTION
**Pull request by benkiel**
Fixes the issue of italics in statics.

Closes #320

### CODE REVIEW

**Comment by benkiel** [comment]
@arrowtype ping.

**Comment by arrowtype** [comment]
Thanks so much, Ben! Sorry for my delay; I was traveling and taking a short mental break from this repo. I am reviewing this and will merge it today. It looks good as far as I can tell from the changes, however!

**Comment by arrowtype** [comment]
Awesome, this seems to be working very well! Thanks so much for closing this. Will make a new release with this shortly.

image

**Comment by benkiel** [comment]
👍I’m onto the other issues

**Pull request merged**
